---
- name: Configure a CA
  hosts: CA_SERVER

  tasks:
  - name: Creating a Certificate Authority
    shell: |
      cd "{{ easyrsa_dir }}/"
      sed -i 's/^.*EASYRSA_REQ_COUNTRY.*/set_var EASYRSA_REQ_COUNTRY      "US"/' vars
      sed -i 's/^.*EASYRSA_REQ_PROVINCE.*/set_var EASYRSA_REQ_PROVINCE      "California"/' vars
      sed -i 's/^.*EASYRSA_REQ_CITY.*/set_var EASYRSA_REQ_CITY      "San Francisco"/' vars
      sed -i 's/^.*EASYRSA_REQ_ORG.*/set_var EASYRSA_REQ_ORG    "SBIT"/' vars
      sed -i 's/^.*EASYRSA_REQ_EMAIL.*/set_var EASYRSA_REQ_EMAIL  "sergey_zyuzev@hotmail.com"/' vars
      sed -i 's/^.*EASYRSA_REQ_OU.*/set_var EASYRSA_REQ_OU      "Community"/' vars
      sed -i 's/^.*EASYRSA_ALGO.*/set_var EASYRSA_ALGO      "ec"/' vars
      sed -i 's/^.*EASYRSA_DIGEST.*/set_var EASYRSA_DIGEST      "sha512"/' vars
      exit 0

  - name: create the root public and private key pair
    command: ./easyrsa --batch build-ca nopass
    args:
      chdir: '{{ easyrsa_dir }}/'
      creates: "{{ easyrsa_dir }}/pki/private/ca.key"