---
- name: Creating the Client Configuration Infrastructure
  hosts: VPN_SERVER

  tasks:
  - name: create directory
    file:
      path: "{{ client_configs_dir }}/files/"
      state: directory
      owner: '{{ username }}'
      group: '{{ username }}'
      mode: '0700'

  - name: Copy base config
    copy:
      src: base.conf
      dest: "{{ client_configs_dir }}/"
      owner: '{{ username }}'
      group: '{{ username }}'
      mode: '0600'
  
  - name: edit base conf
    command: sed -i 's/your_server_ip/{{ ansible_default_ipv4.address }}/' {{ client_configs_dir }}/base.conf
  
  - name: Copy make script
    copy:
      src: make_config.sh
      dest: "{{ client_configs_dir }}/"
      owner: '{{ username }}'
      group: '{{ username }}'
      mode: '0700'
  
  - name: generate client configuration
    command: './make_config.sh {{ item }}'
    args:
      chdir: "{{ client_configs_dir }}/"
      creates: '{{ client_configs_dir }}/files/{{ item }}.ovpn'
    loop: "{{ clients }}"

  - name: Fetch clients configs
    fetch:
      src: '{{ client_configs_dir }}/files/{{ item }}.ovpn'
      dest: client_configs/
      flat: yes
    loop: "{{ clients }}"