- name: Initial server setup
  hosts: ALL_SERVERS
  # become: yes

  tasks:
  - name: Update Upgrade
    become: yes
    apt:
      update_cache: yes
      upgrade: yes
  - name: Install Firewall
    become: yes
    apt:
      name: ufw
      state: latest
      update_cache: true
  
  - name: Enable firewall
    become: yes
    systemd:
      name: ufw
      state: started
      enabled: yes
      
  - name: Setting up a Firewall
    become: yes
    ufw:
      rule: allow
      name: OpenSSH
      state: enabled
