---
- name: Initial server setup
  hosts: ALL_SERVERS
  # become: yes

  tasks:
  - name: Update Upgrade
    become: yes
    apt:
      update_cache: yes
      upgrade: yes
  - name: Install Firewall
    become: yes
    apt:
      name: ufw
      state: latest
      update_cache: true
  
  - name: Enable firewall
    become: yes
    systemd:
      name: ufw
      state: started
      enabled: yes
      
  - name: Setting up a Firewall
    become: yes
    ufw:
      rule: allow
      name: OpenSSH
      state: enabled

  - name: Installing Easy RSA
    become: yes
    apt:
      name: easy-rsa
      state: latest
      update_cache: true
  
  - name: Create directory Easy-RSA
    file:
      path: "{{ easyrsa_dir }}"
      state: directory
      mode: '0700'
      owner: "{{ username }}"
      group: "{{ username }}"

  - name: Create symbolic link
    file:
      src: '/usr/share/easy-rsa/{{ item }}'
      dest: '{{ easyrsa_dir }}/{{ item }}'
      state: link
    loop:
    - easyrsa
    - openssl-easyrsa.cnf
    - vars.example
    - x509-types

  - name: initialize the PKI inside the easy-rsa directory
    command: ./easyrsa init-pki
    args:
      chdir: '{{ easyrsa_dir }}/'
      creates: '{{ easyrsa_dir }}/pki'

  - name: Copy easy-rsa
    copy:
      src: '{{ easyrsa_dir }}/vars.example'
      dest: '{{ easyrsa_dir }}/vars'
      owner: "{{ username }}"
      group: "{{ username }}"
      mode: '0600'
      remote_src: yes
  