---
- name: Singing sertificates
  hosts: ALL_SERVERS

  tasks:
  - name: Fetch certificate request from vpn-server
    fetch:
      src: "{{ easyrsa_dir }}/pki/reqs/server.req"
      dest: buffer/
      flat: yes
    when: ansible_hostname == "vpn-server"
  - name: Copy certificate to ca-server
    copy:
      src: buffer/server.req
      dest: /tmp/
    when: ansible_hostname == "ca-server"

  - name: Import the sertificate request
    command: ./easyrsa import-req /tmp/server.req server
    args:
      chdir: '{{ easyrsa_dir }}/'
      creates: '{{ easyrsa_dir }}/pki/reqs/server.req'
    when: ansible_hostname == "ca-server"
  
  - name: sing the request
    command: ./easyrsa --batch sign-req server server
    args:
      chdir: '{{ easyrsa_dir }}/'
      creates: '{{ easyrsa_dir }}/pki/issued/server.crt'
    when: ansible_hostname == "ca-server"
  
  - name: Fetch certificates of vpn-server and ca-server
    fetch:
      src: "{{ easyrsa_dir }}/pki/{{ item }}"
      dest: buffer/
      flat: yes
    loop:
    - issued/server.crt
    - ca.crt
    when: ansible_hostname == "ca-server"
  - name: Copy sertificates to vpn-server
    copy:
      src: "buffer/{{ item }}"
      dest: /tmp/
    loop:
    - server.crt
    - ca.crt
    when: ansible_hostname == "vpn-server"

  - name: Copy sertificates to OpenVPN
    become: yes
    copy:
      src: "/tmp/{{ item }}"
      dest: "/etc/openvpn/server/{{ item }}"
      remote_src: yes
    loop:
    - server.crt
    - ca.crt
    when: ansible_hostname == "vpn-server"

  - name: Generate the tls-crypt
    command: openvpn --genkey secret ta.key
    args:
      chdir: '{{ easyrsa_dir }}/'
      creates: '{{ easyrsa_dir }}/ta.key'
    when: ansible_hostname == "vpn-server"
  
  - name: Copy tls-crypt key
    become: yes
    copy:
      src: '{{ easyrsa_dir }}/ta.key'
      dest: '/etc/openvpn/server/'
      remote_src: yes
    when: ansible_hostname == "vpn-server"

  - name: Create directory to store client certificate and key
    file:
      path: '{{ client_configs_dir }}/keys'
      state: directory
      mode: '0700'
      owner: '{{ username }}'
      group: '{{ username }}'
    when: ansible_hostname == "vpn-server"

  - name: Generate keys and requests to clients
    command: ./easyrsa --batch gen-req {{ item }} nopass
    args:
      chdir: '{{ easyrsa_dir }}/'
      creates: '{{ easyrsa_dir }}/pki/private/{{ item }}.key'
    loop: "{{ clients }}"
    when: ansible_hostname == "vpn-server"

  - name: Copy client keys to client-config keys
    copy:
      src: '{{ easyrsa_dir }}/pki/private/{{ item }}.key'
      dest: '{{ client_configs_dir }}/keys/'
      owner: '{{ username }}'
      group: '{{ username }}'
      remote_src: yes
    loop: "{{ clients }}"
    when: ansible_hostname == "vpn-server"
  
  - name: Fetch request keys from vpn-server then copy to ca-server
    fetch: 
      src: '{{ easyrsa_dir }}/pki/reqs/{{ item }}.req'
      dest: buffer/
      flat: yes
    loop: "{{ clients }}"
    when: ansible_hostname == "vpn-server"

  - name: Copy keys to ca-server
    copy:
      src: 'buffer/{{ item }}.req'
      dest: /tmp/
    loop: "{{ clients }}"
    when: ansible_hostname == "ca-server"
  
  - name: Import the certificate requests
    command: ./easyrsa import-req /tmp/{{ item }}.req {{ item }}
    args:
      chdir: '{{ easyrsa_dir }}/'
      creates: '{{ easyrsa_dir }}/pki/reqs/{{ item }}.req'
    loop: "{{ clients }}"
    when: ansible_hostname == "ca-server"

  - name: sing the requests
    command: './easyrsa --batch sign-req client {{ item }}'
    args:
      chdir: '{{ easyrsa_dir }}/'
      creates: '{{ easyrsa_dir }}/pki/issued/{{ item }}.crt'
    loop: "{{ clients }}"
    when: ansible_hostname == "ca-server"

  - name: Fetch certificates of clients
    fetch:
      src: "{{ easyrsa_dir }}/pki/issued/{{ item }}.crt"
      dest: buffer/
      flat: yes
    loop: "{{ clients }}"
    when: ansible_hostname == "ca-server"

  - name: Copy client sertificates to vpn-server
    copy:
      src: "buffer/{{ item }}.crt"
      dest: /tmp/
    loop: "{{ clients }}"
    when: ansible_hostname == "vpn-server"

  - name: copy to client config
    copy:
      src: '/tmp/{{ item }}.crt'
      dest: '{{ client_configs_dir }}/keys/'
      owner: '{{ username }}'
      group: '{{ username }}'
      remote_src: yes
    loop: "{{ clients }}"
    when: ansible_hostname == "vpn-server"

  - name: Copy ta to client configs
    copy:
      src: '{{ easyrsa_dir }}/ta.key'
      dest: '{{ client_configs_dir }}/keys/'
      owner: '{{ username }}'
      group: '{{ username }}'
      remote_src: yes
    when: ansible_hostname == "vpn-server"

  - name: Copy ca cert to client configs
    become: yes
    copy:
      src: '/etc/openvpn/server/ca.crt'
      dest: '{{ client_configs_dir }}/keys/'
      owner: '{{ username }}'
      group: '{{ username }}'
      remote_src: yes
    when: ansible_hostname == "vpn-server"